//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50401.0
// 
namespace ProyectoSCA_Navigation.ServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="peticion", Namespace="http://tempuri.org/")]
    public enum peticion : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ingresar_afiliado = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ingresar_empleado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        solicitudModificarPerfil = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        mostrar_perfil_afiliado = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        mostrar_perfil_empleado = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        reingresar_afiliado = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ingresar_aportacion = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        capitalizar_extra = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        login = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ingresar_ocupacion = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ingresar_AOS = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ingresar_monto_AO = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        limite_AV = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ingresar_motivo = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ingresar_parentesco = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ingresar_interes = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        getOcupacion = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        getParentesco = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        getAfiliado = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        getEmpleado = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        getIntereses = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        getMotivos = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        getMontoActual = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        getLimiteActual = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        eliminarOcupacion = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        eliminarMotivo = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        eliminarParentesco = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        eliminarInteres = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        getAfiliadosPagar = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        getControlPagos = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        modificarOcupacion = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        modificarMotivo = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        modificarParentesco = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        modificarInteres = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        getPermisosSeguridad = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        modificarPermisosSeguridad = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        getPermisosPersona = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        getProximoNumeroCertificado = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        insertarAportacionOE = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        pagarAportaciones = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        getAportacion_OE = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        getAportacionesACapitalizar = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        getSaldosACapitalizar = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        capitalizarExtraordinaria = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        buscarAfiliados = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        consultarEstadoDeCuenta = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        getPersonaTemporal = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        reporteAportaciones = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        reporteSaldos = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        modificarPerfil = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        getPerfilNuevo = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        rechazarPerfil = 51,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WSCosecolSoap")]
    public interface WSCosecolSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AgregarPeticion", ReplyAction="*")]
        System.IAsyncResult BeginAgregarPeticion(ProyectoSCA_Navigation.ServiceReference.AgregarPeticionRequest request, System.AsyncCallback callback, object asyncState);
        
        ProyectoSCA_Navigation.ServiceReference.AgregarPeticionResponse EndAgregarPeticion(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarPeticionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarPeticion", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoSCA_Navigation.ServiceReference.AgregarPeticionRequestBody Body;
        
        public AgregarPeticionRequest() {
        }
        
        public AgregarPeticionRequest(ProyectoSCA_Navigation.ServiceReference.AgregarPeticionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarPeticionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ProyectoSCA_Navigation.ServiceReference.peticion codigo_peticion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string String_DK;
        
        public AgregarPeticionRequestBody() {
        }
        
        public AgregarPeticionRequestBody(ProyectoSCA_Navigation.ServiceReference.peticion codigo_peticion, string String_DK) {
            this.codigo_peticion = codigo_peticion;
            this.String_DK = String_DK;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarPeticionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarPeticionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoSCA_Navigation.ServiceReference.AgregarPeticionResponseBody Body;
        
        public AgregarPeticionResponse() {
        }
        
        public AgregarPeticionResponse(ProyectoSCA_Navigation.ServiceReference.AgregarPeticionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarPeticionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AgregarPeticionResult;
        
        public AgregarPeticionResponseBody() {
        }
        
        public AgregarPeticionResponseBody(string AgregarPeticionResult) {
            this.AgregarPeticionResult = AgregarPeticionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSCosecolSoapChannel : ProyectoSCA_Navigation.ServiceReference.WSCosecolSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgregarPeticionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AgregarPeticionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCosecolSoapClient : System.ServiceModel.ClientBase<ProyectoSCA_Navigation.ServiceReference.WSCosecolSoap>, ProyectoSCA_Navigation.ServiceReference.WSCosecolSoap {
        
        private BeginOperationDelegate onBeginAgregarPeticionDelegate;
        
        private EndOperationDelegate onEndAgregarPeticionDelegate;
        
        private System.Threading.SendOrPostCallback onAgregarPeticionCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WSCosecolSoapClient() {
        }
        
        public WSCosecolSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCosecolSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCosecolSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCosecolSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<AgregarPeticionCompletedEventArgs> AgregarPeticionCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ProyectoSCA_Navigation.ServiceReference.WSCosecolSoap.BeginAgregarPeticion(ProyectoSCA_Navigation.ServiceReference.AgregarPeticionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAgregarPeticion(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginAgregarPeticion(ProyectoSCA_Navigation.ServiceReference.peticion codigo_peticion, string String_DK, System.AsyncCallback callback, object asyncState) {
            ProyectoSCA_Navigation.ServiceReference.AgregarPeticionRequest inValue = new ProyectoSCA_Navigation.ServiceReference.AgregarPeticionRequest();
            inValue.Body = new ProyectoSCA_Navigation.ServiceReference.AgregarPeticionRequestBody();
            inValue.Body.codigo_peticion = codigo_peticion;
            inValue.Body.String_DK = String_DK;
            return ((ProyectoSCA_Navigation.ServiceReference.WSCosecolSoap)(this)).BeginAgregarPeticion(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoSCA_Navigation.ServiceReference.AgregarPeticionResponse ProyectoSCA_Navigation.ServiceReference.WSCosecolSoap.EndAgregarPeticion(System.IAsyncResult result) {
            return base.Channel.EndAgregarPeticion(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndAgregarPeticion(System.IAsyncResult result) {
            ProyectoSCA_Navigation.ServiceReference.AgregarPeticionResponse retVal = ((ProyectoSCA_Navigation.ServiceReference.WSCosecolSoap)(this)).EndAgregarPeticion(result);
            return retVal.Body.AgregarPeticionResult;
        }
        
        private System.IAsyncResult OnBeginAgregarPeticion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ProyectoSCA_Navigation.ServiceReference.peticion codigo_peticion = ((ProyectoSCA_Navigation.ServiceReference.peticion)(inValues[0]));
            string String_DK = ((string)(inValues[1]));
            return this.BeginAgregarPeticion(codigo_peticion, String_DK, callback, asyncState);
        }
        
        private object[] OnEndAgregarPeticion(System.IAsyncResult result) {
            string retVal = this.EndAgregarPeticion(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAgregarPeticionCompleted(object state) {
            if ((this.AgregarPeticionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AgregarPeticionCompleted(this, new AgregarPeticionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AgregarPeticionAsync(ProyectoSCA_Navigation.ServiceReference.peticion codigo_peticion, string String_DK) {
            this.AgregarPeticionAsync(codigo_peticion, String_DK, null);
        }
        
        public void AgregarPeticionAsync(ProyectoSCA_Navigation.ServiceReference.peticion codigo_peticion, string String_DK, object userState) {
            if ((this.onBeginAgregarPeticionDelegate == null)) {
                this.onBeginAgregarPeticionDelegate = new BeginOperationDelegate(this.OnBeginAgregarPeticion);
            }
            if ((this.onEndAgregarPeticionDelegate == null)) {
                this.onEndAgregarPeticionDelegate = new EndOperationDelegate(this.OnEndAgregarPeticion);
            }
            if ((this.onAgregarPeticionCompletedDelegate == null)) {
                this.onAgregarPeticionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAgregarPeticionCompleted);
            }
            base.InvokeAsync(this.onBeginAgregarPeticionDelegate, new object[] {
                        codigo_peticion,
                        String_DK}, this.onEndAgregarPeticionDelegate, this.onAgregarPeticionCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ProyectoSCA_Navigation.ServiceReference.WSCosecolSoap CreateChannel() {
            return new WSCosecolSoapClientChannel(this);
        }
        
        private class WSCosecolSoapClientChannel : ChannelBase<ProyectoSCA_Navigation.ServiceReference.WSCosecolSoap>, ProyectoSCA_Navigation.ServiceReference.WSCosecolSoap {
            
            public WSCosecolSoapClientChannel(System.ServiceModel.ClientBase<ProyectoSCA_Navigation.ServiceReference.WSCosecolSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginAgregarPeticion(ProyectoSCA_Navigation.ServiceReference.AgregarPeticionRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("AgregarPeticion", _args, callback, asyncState);
                return _result;
            }
            
            public ProyectoSCA_Navigation.ServiceReference.AgregarPeticionResponse EndAgregarPeticion(System.IAsyncResult result) {
                object[] _args = new object[0];
                ProyectoSCA_Navigation.ServiceReference.AgregarPeticionResponse _result = ((ProyectoSCA_Navigation.ServiceReference.AgregarPeticionResponse)(base.EndInvoke("AgregarPeticion", _args, result)));
                return _result;
            }
        }
    }
}
